name: Run PR Checks
on: pull_request
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install OS Deps
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y libcurl4-openssl-dev
      - name: Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: test
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install OS Deps
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y libcurl4-openssl-dev
      - name: Assemble
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          arguments: assemble
          properties: |
            org.gradle.vfs.watch=false
            org.gradle.vfs.verbose=false